# Generated by Django 6.0 on 2025-12-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Produto')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código (EAN/Ref)')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário (R$)')),
                ('ncm', models.CharField(help_text='Ex: 25232910 para Cimento', max_length=8, verbose_name='NCM (Imposto)')),
                ('estoque_atual', models.IntegerField(default=0, verbose_name='Qtd em Estoque')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
