# Generated by Django 6.0 on 2025-12-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='ncm',
            field=models.CharField(help_text='Código de 8 dígitos. Ex: 25232910 para Cimento', max_length=8, verbose_name='NCM (Imposto)'),
        ),
    ]
