# Generated by Django 6.0 on 2025-12-30 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notafiscal_empresa'),
        ('estoque', '0002_alter_produto_ncm'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Loja/Empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.CharField(max_length=20, verbose_name='Código (EAN/Ref)'),
        ),
        migrations.AlterUniqueTogether(
            name='produto',
            unique_together={('empresa', 'codigo')},
        ),
    ]
