# Generated by Django 6.0 on 2025-12-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_nota', models.CharField(max_length=100, unique=True, verbose_name='ID Nuvem Fiscal')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('serie', models.IntegerField(verbose_name='Série')),
                ('data_emissao', models.DateTimeField(auto_now_add=True, verbose_name='Data Emissão')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-data_emissao'],
            },
        ),
    ]
