# Generated by Django 6.0 on 2025-12-27 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_nota', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Nuvem Fiscal')),
                ('numero', models.IntegerField(default=0, verbose_name='Número')),
                ('serie', models.IntegerField(default=0, verbose_name='Série')),
                ('chave', models.CharField(blank=True, max_length=50, null=True, verbose_name='Chave de Acesso')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total (R$)')),
                ('status', models.CharField(default='PENDENTE', max_length=50)),
                ('url_pdf', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link do PDF')),
                ('url_xml', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link do XML')),
                ('data_emissao', models.DateTimeField(auto_now_add=True, verbose_name='Data Emissão')),
            ],
            options={
                'ordering': ['-data_emissao'],
            },
        ),
    ]
