# Generated by Django 6.0 on 2025-12-30 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Razão Social / Nome Fantasia')),
                ('cnpj', models.CharField(max_length=14, unique=True, verbose_name='CNPJ (apenas números)')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual')),
                ('crt', models.CharField(choices=[('1', '1 - Simples Nacional'), ('2', '2 - Simples Nacional (excesso de sublimite)'), ('3', '3 - Regime Normal (Lucro Presumido/Real)')], default='1', max_length=1, verbose_name='Regime Tributário (CRT)')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('logradouro', models.CharField(max_length=100, verbose_name='Endereço')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('bairro', models.CharField(max_length=50, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('nuvem_client_id', models.CharField(max_length=255, verbose_name='Client ID (Nuvem Fiscal)')),
                ('nuvem_client_secret', models.CharField(max_length=255, verbose_name='Client Secret (Nuvem Fiscal)')),
            ],
            options={
                'verbose_name': 'Empresa / Loja',
                'verbose_name_plural': 'Empresas / Lojas',
            },
        ),
        migrations.AlterModelOptions(
            name='notafiscal',
            options={'ordering': ['-data_emissao'], 'verbose_name': 'Nota Fiscal', 'verbose_name_plural': 'Notas Fiscais'},
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='data_emissao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Emissão'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='status',
            field=models.CharField(default='PENDENTE', max_length=50, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa/Loja')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
