# Generated by Django 6.0 on 2025-12-30 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_empresa_alter_notafiscal_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa Emitente'),
            preserve_default=False,
        ),
    ]
