# Generated by Django 6.0 on 2025-12-31 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_empresa_cor_cabecalho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cor_cabecalho',
            field=models.CharField(default='#10295a', help_text='Ex: #FF0000 para vermelho', max_length=10, verbose_name='Cor do Cabeçalho (Hex)'),
        ),
    ]
