# Generated by Django 6.0 on 2025-12-31 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_empresa_cor_cabecalho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='cor_cabecalho',
        ),
        migrations.AddField(
            model_name='empresa',
            name='cor_primaria',
            field=models.CharField(default='#10295a', help_text='Ex: #FF0000 para vermelho', max_length=10, verbose_name='Cor Primaria (Hex)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cor_secundaria',
            field=models.CharField(default='#10295a', help_text='Ex: #FF0000 para vermelho', max_length=10, verbose_name='Cor Secundaria (Hex)'),
        ),
    ]
