# Generated by Django 6.0 on 2025-12-31 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_empresa_cor_cabecalho_empresa_cor_primaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='nome_fantasia',
            field=models.CharField(default=1, max_length=100, verbose_name='Nome Fantasia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Razão Social'),
        ),
    ]
