# Generated by Django 6.0 on 2025-12-31 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cliente_notafiscal_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='nuvem_client_id',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='nuvem_client_secret',
        ),
        migrations.AddField(
            model_name='empresa',
            name='ambiente',
            field=models.CharField(choices=[('homologacao', 'Homologação (Testes)'), ('producao', 'Produção (Valendo!)')], default='homologacao', max_length=20, verbose_name='Ambiente Nuvem Fiscal'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cod_municipio',
            field=models.CharField(default='2112209', help_text='Consulte em: https://www.ibge.gov.br/explica/codigos-dos-municipios.php', max_length=7, verbose_name='Código IBGE do Município'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nuvem_client_id_homologacao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Client ID (Nuvem Fiscal) - Testes'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nuvem_client_id_producao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Client ID (Nuvem Fiscal) - Real'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nuvem_client_secret_homologacao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Client Secret (Nuvem Fiscal) - Testes'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nuvem_client_secret_producao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Client Secret (Nuvem Fiscal) - Real'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cor_primaria',
            field=models.CharField(default='#10295a', help_text='Ex: #10295a para azul escuro', max_length=10, verbose_name='Cor Primária (Hex)'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cor_secundaria',
            field=models.CharField(default='#dd5114', help_text='Ex: #dd5114 para laranja', max_length=10, verbose_name='Cor Secundária (Hex)'),
        ),
    ]
