# Generated by Django 6.0 on 2025-12-31 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_empresa_nuvem_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='ambiente',
            field=models.CharField(choices=[('homologacao', 'Homologação (Testes)'), ('producao', 'Produção (Real)')], default='homologacao', max_length=20, verbose_name='Ambiente'),
        ),
    ]
