# Generated by Django 6.0 on 2026-01-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_notafiscal_ambiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cod_municipio',
            field=models.CharField(blank=True, help_text='Código de 7 dígitos. Ex: 2112209 para Timon-MA', max_length=7, null=True, verbose_name='Código IBGE'),
        ),
    ]
