# Generated by Django 6.0 on 2026-01-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_cliente_cod_municipio'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='forma_pagamento',
            field=models.CharField(choices=[('01', 'Dinheiro'), ('03', 'Cartão de Crédito'), ('04', 'Cartão de Débito'), ('17', 'PIX')], default='01', max_length=2, verbose_name='Forma de Pagamento'),
        ),
    ]
