# Generated by Django 6.0 on 2026-01-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_notafiscal_forma_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='apelido',
            field=models.CharField(blank=True, help_text="Para simplificar em telas pequenas. Ex: 'João da Silva'", max_length=30, null=True, verbose_name='Apelido / Nome Curto'),
        ),
    ]
