# Generated by Django 6.0 on 2026-04-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_cliente_apelido'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='certificado_a1_pfx_homologacao',
            field=models.BinaryField(blank=True, null=True, verbose_name='PFX Homologação (cifrado)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='certificado_a1_pfx_producao',
            field=models.BinaryField(blank=True, null=True, verbose_name='PFX Produção (cifrado)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='certificado_a1_senha_homologacao',
            field=models.BinaryField(blank=True, null=True, verbose_name='Senha PFX Homologação (cifrado)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='certificado_a1_senha_producao',
            field=models.BinaryField(blank=True, null=True, verbose_name='Senha PFX Produção (cifrado)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='certificado_a1_validade_homologacao',
            field=models.DateField(blank=True, null=True, verbose_name='Validade Cert. Homologação'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='certificado_a1_validade_producao',
            field=models.DateField(blank=True, null=True, verbose_name='Validade Cert. Produção'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='csc_id_homologacao',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CSC ID Homologação'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='csc_id_producao',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CSC ID Produção'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='csc_token_homologacao',
            field=models.BinaryField(blank=True, null=True, verbose_name='CSC Token Homologação (cifrado)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='csc_token_producao',
            field=models.BinaryField(blank=True, null=True, verbose_name='CSC Token Produção (cifrado)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='emissor_fiscal',
            field=models.CharField(choices=[('nuvem', 'Nuvem Fiscal (API)'), ('direto', 'SEFAZ Direto')], default='nuvem', help_text='Alternar entre API da Nuvem Fiscal e comunicação direta com a SEFAZ.', max_length=10, verbose_name='Emissor Fiscal'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='serie_nfce_homologacao',
            field=models.IntegerField(default=2, verbose_name='Série NFC-e Homologação'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='serie_nfce_producao',
            field=models.IntegerField(default=3, verbose_name='Série NFC-e Produção'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='data_cancelamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Cancelamento'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='protocolo_autorizacao',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Protocolo de Autorização'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='protocolo_cancelamento',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Protocolo Cancelamento'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='qrcode_url',
            field=models.URLField(blank=True, max_length=700, null=True, verbose_name='URL QR Code'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='xml_assinado',
            field=models.TextField(blank=True, null=True, verbose_name='XML + Protocolo'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='xml_cancelamento',
            field=models.TextField(blank=True, null=True, verbose_name='XML Cancelamento'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ambiente',
            field=models.CharField(choices=[('homologacao', 'Homologação (Testes)'), ('producao', 'Produção (Valendo!)')], default='homologacao', max_length=20, verbose_name='Ambiente de Emissão'),
        ),
    ]
