# Generated by Django 6.0 on 2026-05-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_empresa_certificado_a1_pfx_homologacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='numero_nfce_homologacao',
            field=models.IntegerField(default=0, help_text='Último número emitido. Ajuste se o banco foi resetado.', verbose_name='Último nº NFC-e Homologação'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='numero_nfce_producao',
            field=models.IntegerField(default=0, help_text='Último número emitido. Ajuste se o banco foi resetado.', verbose_name='Último nº NFC-e Produção'),
        ),
    ]
